### ISSUE TITLE
docker build fails

### ISSUE THREAD

**Issue by javierlinked** [pereiren/dotnet-template-onion#1]
Upon run 
```docker build -f Dockerfile ..```

process fails because wrong .csproj file is referenced.

```Sending build context to Docker daemon  27.85MB
Step 1/17 : FROM mcr.microsoft.com/dotnet/aspnet:5.0-buster-slim AS base
 ---> c3a51e51a0f9
Step 2/17 : WORKDIR /app
 ---> Using cache
 ---> 9790ebeae196
Step 3/17 : EXPOSE 80
 ---> Using cache
 ---> 1f4abed4e62f
Step 4/17 : EXPOSE 443
 ---> Using cache
 ---> 6cc799c8153d
Step 5/17 : FROM mcr.microsoft.com/dotnet/sdk:5.0-buster-slim AS build
 ---> dd6f8be8f903
Step 6/17 : WORKDIR /src
 ---> Using cache
 ---> bf4d464ea7f1
Step 7/17 : COPY ["Onion/Onion.csproj", "Onion/"]
COPY failed: file not found in build context or excluded by .dockerignore: stat Onion/Onion.csproj: file does not exist```

**Comment by pereiren** [comment]
Hey Javier!

That COPY is a little bit different that the one provided in the Dockerfile https://github.com/pereiren/dotnet-template-onion/blob/84c11a18d7ca6ce67076db29c447fb7fd9730bc9/src/Dotnet.Onion.Template.API/Dockerfile#L10

Did you create it using the dotnet CLI template or just a fork?

Thanks

**Comment by javierlinked** [comment]
I followed `README` steps, so first I executed:
`dotnet new dotnet_template_onion -n Onion`
inside `Onion/src/Onion.API/` exists both `dockerfile` and `Onion.API.csproj`

COPY points to `Dotnet.Onion.Template/Dotnet.Onion.Template.csproj`, but that .csproj does not exist, but the other 4 (API, Infrastructure, Application and Domain).

Am I clear? Thanks.

**Comment by pereiren** [comment]
Sure, I'll take a look at it! Thank you for reporting it!

**Comment by javierlinked** [comment]
Done!

**Comment by pereiren** [comment]
> Done!

@javierlinked Thank you very much!
